name = "image-sharpener-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-08-01"

[build]
command = "npm --prefix frontend ci --no-audit --no-fund && npm --prefix frontend run build"

[site]
bucket = "frontend/dist"


